# Generated by Codex for the premium showroom upgrade.

from django.conf import settings
from django.core.validators import FileExtensionValidator, MinValueValidator
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify

import car.models
import django.db.models.deletion


def unique_slug(model, base_value, instance_id=None):
    base_slug = slugify(base_value) or "item"
    slug = base_slug
    counter = 2
    queryset = model.objects.all()
    if instance_id is not None:
        queryset = queryset.exclude(pk=instance_id)
    while queryset.filter(slug=slug).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    return slug


def migrate_brands_and_images(apps, schema_editor):
    Brand = apps.get_model("car", "Brand")
    Car = apps.get_model("car", "Car")
    CarImage = apps.get_model("car", "CarImage")

    for car in Car.objects.all():
        brand_name = (car.brand or "").strip() or "Unknown"
        brand = Brand.objects.filter(name=brand_name).first()
        if brand is None:
            brand = Brand.objects.create(
                name=brand_name,
                slug=unique_slug(Brand, brand_name),
            )

        car.brand_ref_id = brand.id
        car.slug = unique_slug(Car, f"{brand_name}-{car.name}", car.pk)
        if not car.is_featured:
            car.is_featured = True
        car.save(update_fields=["brand_ref", "slug", "is_featured"])

        image_fields = [
            ("main_image", car.main_image),
            ("image1", car.image1),
            ("image2", car.image2),
            ("image3", car.image3),
        ]
        image_index = 0
        primary_assigned = False
        for field_name, image_value in image_fields:
            if not image_value:
                continue
            CarImage.objects.create(
                car_id=car.id,
                image=image_value,
                alt_text=f"{brand_name} {car.name} image {image_index + 1}",
                sort_order=image_index,
                is_primary=(field_name == "main_image") or not primary_assigned,
            )
            image_index += 1
            primary_assigned = True


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="brands/",
                        validators=[
                            FileExtensionValidator(["jpg", "jpeg", "png", "webp", "avif"]),
                            car.models.validate_image_size,
                        ],
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="car.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "car", "preferred_date")}},
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to="cars/",
                        validators=[
                            FileExtensionValidator(["jpg", "jpeg", "png", "webp", "avif"]),
                            car.models.validate_image_size,
                        ],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="car.car",
                    ),
                ),
            ],
            options={"ordering": ["-is_primary", "sort_order", "pk"]},
        ),
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer_inquiries",
                        to="car.car",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="car.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "car")}},
        ),
        migrations.AddField(
            model_name="car",
            name="brand_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="car.brand",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="car",
            name="horsepower",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="seating_capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="car",
            name="top_speed",
            field=models.PositiveIntegerField(blank=True, help_text="km/h", null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.CharField(help_text="Mileage (e.g. 15 km/l)", max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_year",
            field=models.PositiveIntegerField(help_text="Manufacturing year"),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price in INR",
                max_digits=12,
                validators=[MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(migrate_brands_and_images, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="car",
            name="brand_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="car.brand",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.RemoveField(model_name="car", name="brand"),
        migrations.RemoveField(model_name="car", name="image1"),
        migrations.RemoveField(model_name="car", name="image2"),
        migrations.RemoveField(model_name="car", name="image3"),
        migrations.RemoveField(model_name="car", name="main_image"),
        migrations.RenameField(model_name="car", old_name="brand_ref", new_name="brand"),
    ]
